# Generated by Django 4.2.3 on 2023-07-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='create_data',
        ),
    ]
